image: ruby:2.4.2

cache:
  paths:
  - vendor

test:
  script:
  - bundle install --path vendor
  - bundle exec middleman build
  except:
    - master

pages:
  script:
  - bundle install --path vendor
  - bundle exec middleman build
  artifacts:
    paths:
    - public
  only:
  - master
